### ISSUE TITLE
Dependencies?

### ISSUE THREAD

**Issue by ewerlopes** [seemk/FastHumanDetection#1]
Hi!

I am interested in this project!
Is it able to run on Linux or Mac?

Thanks.

**Comment by seemk** [comment]
Hi,

The library runs on Linux, I haven't tested on OSX. On Linux it has no external dependencies, on Windows the CMake file looks for Kinect V2 SDK. Other dependencies are bundled with the source. The library itself expects Kinect V2 depth images (512x424, 16 bit depth), on Linux I've just used an SQLite database of depth frame data.

**Comment by ewerlopes** [comment]
HI!

Thanks for your reply!
Well, nice to hear that it can work on a linux environment! I should test it.. I am wondering how fast is the application per se... Also, can I maintain the frame rate close to what the SDK can give? On linux I am using libfrenect2 to get  the depth data from the Kinect v2.

Thanks.

**Comment by seemk** [comment]
The detection time is around 5 ms per frame on i7-720 QM (a 2009 laptop cpu) with 4 OpenMP threads enabled (compile time parameter at src/fhd_config.h).

**Comment by ewerlopes** [comment]
Ow... Very, very nice!
Thanks for the info!
